services:
    server:
        build:
            context: .
            dockerfile: docker/Dockerfile-chap3
        privileged: true
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet2:
              ipv4_address: 172.29.0.10
        depends_on:
            - "router"
        sysctls:
          - net.ipv4.tcp_congestion_control=reno
        command: bash -c "/docker/server.sh && sleep infinity"
    middle:
        build:
            context: .
            dockerfile: docker/Dockerfile-chap3
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet2:
              ipv4_address: 172.29.0.11
        depends_on:
            - "router"
        sysctls:
          - net.ipv4.ip_forward=1
          - net.ipv4.tcp_congestion_control=reno
        command: bash -c "/docker/middle.sh && python3 /app/middle.py || sleep infinity"
    router:
        build:
            context: .
            dockerfile: docker/Dockerfile-chap3
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet1:
              ipv4_address: 172.28.0.254
            subnet2:
              ipv4_address: 172.29.0.254
        sysctls:
          - net.ipv4.ip_forward=1
          - net.ipv4.tcp_congestion_control=reno
        command: bash -c "/docker/router.sh && sleep infinity" # "/elocal/capitolul3/src/alter_packages.sh"
    client:
        build:
            context: .
            dockerfile: docker/Dockerfile-chap3
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet1:
              ipv4_address: 172.28.0.10
        depends_on:
            - "router"
            - "server"
        sysctls:
          - net.ipv4.tcp_congestion_control=reno
        command: bash -c "/docker/client.sh && sleep infinity"
networks:
    subnet1:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
    subnet2:
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/24
